name: fundl-dev
channels:
- conda-forge
- defaults
- ericmjl
dependencies:
- python=3.7
- autograd
- black
- conda
- hypothesis
- isort
- jax
- jaxlib
- jupyter
- jupyterlab
- mypy
- numpy
- pycodestyle
- pydocstyle
- pylint
- pytest
- pytest-xdist
- scipy
- pylint
- jax
- jaxlib
- autograd
