name: fundl-dev
channels:
- conda-forge
- defaults
- ericmjl
dependencies:
- python=3.7
- autograd=1.3
- black=19.3b0
- conda=4.7.11
- fastcache=1.1.0
- hypothesis=4.35.0
- isort=4.3.21
- jax=0.1.44
- jaxlib=0.1.28
- jupyter=1.0.0
- jupyterlab=1.1.1
- mypy=0.720
- numpy=1.17.2
- pandas=0.25.1
- pycodestyle=2.5.0
- pydocstyle=4.0.1
- pylint=2.3.1
- pytest-xdist=1.29.0
- pytest=5.1.2
- scipy=1.3.1
